### ISSUE TITLE
Different gain and bias at each time step

### ISSUE THREAD

**Issue by frsong** [pbhatia243/tf-layer-norm#1]
Maybe I'm misunderstanding something, but in the paper, the same gain and bias are used for all time steps; otherwise this creates a lot of parameters for long sequences.

**Comment by pbhatia243** [comment]
Yes, because parameters are initialized in cell, they are initialized only once and used through the model similar to parameters of LSTM or GRU .

**Comment by frsong** [comment]
Thanks for your quick response! But I don't think that is what's happening.
Using tf.trainable_variables shows that a new set is being created for each
time step (screenshot attached).

Best,
Francis

**Comment by pbhatia243** [comment]
Thanks for pointing it out. I have fixed the issue.
